name: ci
on:
  push:
    branches:
      - amur # deployment branch

  pull_request:
    types: [opened, synchronize]
    branches:
      - master
      - amur

jobs:
  node-webservice:
    uses: proxima-one/github-workflows/.github/workflows/node-webservice.yml@master
    with:
      appName: mangrove
      dockerfilePath: ./Dockerfile
      pulumiPath: ./deploy
      preview: ${{ github.event_name == 'pull_request' }}
      publish: ${{ github.base_href == 'amur' || github.ref == 'amur' }}
      deploy: ${{ github.base_href == 'amur' || github.ref == 'amur' }}
    secrets:
      CI_NPM_TOKEN: ${{ secrets.CI_NPM_TOKEN }}
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
