name: ci
on:
  workflow_dispatch:
  push:
    branches: 
      - master
      - develop
      - 'run-ci/**'
  pull_request_target:
    branches: [ master, develop, test-pr ]
    types: [opened, synchronize, reopened, labeled]
jobs:
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

  check:
    if: always()

    needs:
    - quick-check

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}